from __future__ import annotations
from typing import Tuple, List, Optional, Any
import numpy as np
from numpy.typing import NDArray

__version__: str

class time_tag:
    """Mantis time_tag class. class is split into full seconds and fractional for increased accuracy"""
    def __init__(self) -> None: ...
    def __init__(self, full_secs: int, frac_secs: float) -> None: ...
    def __init__(self, full_secs: int) -> None: ...
    @property
    def full_secs(self) -> int: ...
    @property
    def frac_secs(self) -> float: ...
    def __add__(self, other: time_tag) -> time_tag: ...
    def __sub__(self, other: time_tag) -> time_tag: ...
    def __iadd__(self, other: time_tag) -> time_tag: ...
    def __isub__(self, other: time_tag) -> time_tag: ...

class mtx_metadata:
    def __init__(self) -> None: ...
    timeout: float
    start_of_burst: bool
    end_of_burst: bool
    has_time_spec: bool
    time_spec: time_tag
    eov_positions: List[int]
    def set_time_spec(self, time_spec: time_tag) -> None: ...

class mrx_metadata:
    eov_positions_size: int
    eov_positions_count: int
    fragment_offset: int
    time_spec: time_tag
    timeout: float
    start_of_burst: bool
    end_of_burst: bool
    has_time_spec: bool
    more_fragments: bool
    out_of_sequence: bool
    one_packet: bool
    code: metadata_errors.mrx_metadata_error_codes
    def set_time_spec(self, _time_spec: time_tag) -> None: ...

class msdr_params:
    """struct that contains all the parameters needed to find, init, and configure an SDR."""
    def __init__(self) -> None: ...
    type: str
    serial: str
    name: str
    product: str
    addr: str
    fpga: str
    master_clock_rate: str
    send_buff_size: str
    recv_buff_size: str
    clock_source: str
    time_source: str
    def get_find_args(self) -> str: ...
    def get_config_args(self) -> str: ...
    @staticmethod
    def compare(specific: msdr_params, generic: msdr_params) -> bool: ...
    @staticmethod
    def from_str(args: str, delimiter: str = ";") -> Tuple[errors.error_code, msdr_params]: ...
    def __repr__(self) -> str: ...

class mrx_channel:
    def healthcheck(self) -> bool: ...
    def sync(self, time_stamp: time_tag) -> errors.error_code: ...
    def get_time_now(self) -> time_tag: ...
    def get_channel_num(self) -> int: ...
    def is_valid(self) -> bool: ...
    def invalidate(self) -> None: ...
    def set_rate(self, rate: float) -> float: ...
    def get_rate(self) -> float: ...
    def set_freq(self, freq: float, lo: Optional[float] = None) -> float: ...
    def get_freq(self) -> float: ...
    def set_gain(self, gain: float) -> float: ...
    def get_gain(self) -> float: ...
    def get_valid_sample_rates(self) -> List[float]: ...
    def set_clock_source(self, clock_source: str) -> None: ...
    def set_time_source(self, time_source: str) -> None: ...
    def can_set_power_ref(self) -> bool: ...
    def set_power_ref(self, power_dbm: float) -> Tuple[float, errors.error_code]: ...
    def get_power_ref(self) -> Tuple[float, errors.error_code]: ...
    def get_params(self) -> msdr_params: ...
    def receive(self, buffer: NDArray[np.complex64], metadata: mrx_metadata) -> int: ...

class mtx_channel:
    def healthcheck(self) -> bool: ...
    def sync(self, time_stamp: time_tag) -> errors.error_code: ...
    def get_time_now(self) -> time_tag: ...
    def get_channel_num(self) -> int: ...
    def is_valid(self) -> bool: ...
    def invalidate(self) -> None: ...
    def set_rate(self, rate: float) -> float: ...
    def get_rate(self) -> float: ...
    def set_freq(self, freq: float, lo: Optional[float] = None) -> float: ...
    def get_freq(self) -> float: ...
    def set_gain(self, gain: float) -> float: ...
    def get_gain(self) -> float: ...
    def get_valid_sample_rates(self) -> List[float]: ...
    def set_clock_source(self, clock_source: str) -> None: ...
    def set_time_source(self, time_source: str) -> None: ...
    def can_set_power_ref(self) -> bool: ...
    def set_power_ref(self, power_dbm: float) -> Tuple[float, errors.error_code]: ...
    def get_power_ref(self) -> Tuple[float, errors.error_code]: ...
    def get_params(self) -> msdr_params: ...
    def send(self, buffer: NDArray[np.complex64], metadata: mtx_metadata) -> None: ...
    def recv_async_message(self) -> metadata_errors.async_mtx_metadata_error_codes: ...

class device_manager:
    @staticmethod
    def get_instance() -> device_manager: ...
    def init(self, num: int, msdr_params: msdr_params) -> errors.error_code: ...
    def init_all(self, msdr_params: msdr_params) -> errors.error_code: ...
    def get_tx_channel(self, msdr_params: msdr_params, channel_num: int) -> Tuple[errors.error_code, mtx_channel]: ...
    def get_rx_channel(self, msdr_params: msdr_params, channel_num: int) -> Tuple[errors.error_code, mrx_channel]: ...
    def find(self, params: msdr_params) -> List[msdr_params]: ...
    def get_connected(self) -> List[msdr_params]: ...
    def __repr__(self) -> str: ...

class errors:
    class error_code:
        SUCCESS: errors.error_code
        NO_SDRS_CONNECTED: errors.error_code
        NO_SDRS_FOUND: errors.error_code
        INSUFFICIENT_SDRS_FOUND: errors.error_code
        NO_MATCHING_SDR: errors.error_code
        INVALID_SDR: errors.error_code
        INVALID_MCR: errors.error_code
        INVALID_ARGUMENT: errors.error_code
        NO_TX_CHANNELS: errors.error_code
        NO_RX_CHANNELS: errors.error_code
        INSUFFICIENT_TX_CHANNELS: errors.error_code
        INSUFFICIENT_RX_CHANNELS: errors.error_code
        POWER_REF_UNAVAILABLE: errors.error_code
        SOCKET_CONECTION_FAILURE: errors.error_code
        TOTAL_SOCKET_SEND_FAILURE: errors.error_code
        TOTAL_SOCKET_RECV_FAILURE: errors.error_code
        PARTIAL_SOCKET_SEND_FAILURE: errors.error_code
        PARTIAL_SOCKET_RECV_FAILURE: errors.error_code
        FAILED_TO_ACCEPT_CLIENT: errors.error_code
        FAILED_TO_GET_SOCKET_FD: errors.error_code
        FAILED_TO_BIND: errors.error_code
        FAILED_TO_LISTEN: errors.error_code
        CHANNEL_IN_USE: errors.error_code
        TIMEOUT: errors.error_code
        INVALID_TIME_SOURCE: errors.error_code
    @staticmethod
    def mantis_errno(code: error_code) -> str: ...

class metadata_errors:
    class async_mtx_metadata_error_codes:
        BURST_ACK: metadata_errors.async_mtx_metadata_error_codes
        UNDERFLOW: metadata_errors.async_mtx_metadata_error_codes
        SEQ_ERROR: metadata_errors.async_mtx_metadata_error_codes
        LATE: metadata_errors.async_mtx_metadata_error_codes
        UNDERFLOW_IN_PACKET: metadata_errors.async_mtx_metadata_error_codes
        SEQ_ERROR_IN_BURST: metadata_errors.async_mtx_metadata_error_codes
        USER_PAYLOAD: metadata_errors.async_mtx_metadata_error_codes
    class mrx_metadata_error_codes:
        NO_ERROR: metadata_errors.mrx_metadata_error_codes
        TIMEOUT: metadata_errors.mrx_metadata_error_codes
        LATE: metadata_errors.mrx_metadata_error_codes
        BROKEN_CHAIN: metadata_errors.mrx_metadata_error_codes
        OVERFLOW: metadata_errors.mrx_metadata_error_codes
        ALIGNMENT: metadata_errors.mrx_metadata_error_codes
        BAD_PACKET: metadata_errors.mrx_metadata_error_codes
    @staticmethod
    def mantis_errno(code: async_mtx_metadata_error_codes) -> str: ...
    @staticmethod
    def mantis_errno(code: mrx_metadata_error_codes) -> str: ...

class utils:
    @staticmethod
    def pinfo(msg: str) -> None: ...
    @staticmethod
    def perror(msg: str) -> None: ...
    @staticmethod
    def pwarn(msg: str) -> None: ...
    @staticmethod
    def get_sample_size() -> int: ...
